export const PLAYER_STATES = {
  LOADING: 'LOADING',
  READY: 'READY',
  PAUSED: 'PAUSED',
  PLAYING: 'PLAYING'
};

export const PLAYER_EVENTS = {
  PRESS_PLAY: 'PRESS_PLAY',
  PRESS_PAUSE: 'PRESS_PAUSE',
  PRESS_NEXT: 'PRESS_NEXT',
  PRESS_PREVIOUS: 'PRESS_PREVIOUS'
};

export const PLAYER_ACTIONS = {
  SET_STATE: 'SET_STATE',
  SET_QUEUE: 'SET_QUEUE',
  PLAY_SONG: 'PLAY_SONG',
  PAUSE_SONG: 'PAUSE_SONG',
  RESET_SONG: 'RESET_SONG',
  NEXT_SONG: 'NEXT_SONG',
  PREVIOUS_SONG: 'PREVIOUS_SONG',
  SHUFFLE: 'SHUFFLE',
  UNSHUFFLE: 'UNSHUFFLE'
};
