export const PLAYER_STATES = {
  LOADING: 'LOADING',
  PAUSED: 'PAUSED',
  PLAYING: 'PLAYING'
};

export const PLAYER_ACTIONS = {
  LOAD_IFRAMES: 'LOAD_IFRAMES',
  SET_QUEUE: 'SET_QUEUE',
  PLAY_SONG: 'PLAY_SONG',
  PAUSE_SONG: 'PAUSE_SONG',
  RESET_SONG: 'RESET_SONG',
  NEXT_SONG: 'NEXT_SONG',
  PREVIOUS_SONG: 'PREVIOUS_SONG',
  SHUFFLE: 'SHUFFLE',
  UNSHUFFLE: 'UNSHUFFLE'
};
