options:
  cache-config: false
  merge-default-rules: false
  formatter: stylish
  max-warnings: 50
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.*'
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    - style: uppercase
  indentation:
    - 2
    - size: 2
  property-sort-order:
    - 1
