language: node_js

node_js:
  - "5.1"
  - "4.2"
  - "4.1"

cache:
  directories:
    - node_modules

before_script:
  # start firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make lint
  - make build
  - make run > /dev/null &
  - sleep 25
  - make test_full
