language: node_js
node_js:
  - '6.1'
env:
  global:
    - NODE_ENV=production
    - SURGE_DOMAIN=dribbling-wave.surge.sh
    - secure: dChQOsz51Yv7nLwg9C7zekCLLm6xnq5KCbqTUtDg285ZmIYLhNb98VAhd6sbSp1m8AM8UelpzuEnFa5idUzhDGJu4JYtLKR5WsQoQaOwwtTFLsTbWBoCnT2rGOJd8gFMy2T8x34mCpfElRebG85kltytq2szCk3ma/wzHFqlaIGg6g9Qc+9J6QshYYdvXyxFZerY4aYEQIKdnVB91tVLb+1KGuZbH+PYDAeElLFvpx1uI8aqdMZB7TghBGYQzMbpgYozAZ/WsvABqbT4asRoPAScF+T4VygTIfEIigMdlyCdNp8OLXbAkUp2F9ggLbrQ7iW9JUVl/u5tC7sck7ZkVwUunpT6YYsv0vglUx8Q/ZupZreTIfo4iVXrRVsrKrfbqpBMItFTMf4G7zViw23xmP448X56daIrEl83jOH1jsTNQPITxKzu8UQL0NCceS3mZ2hGQxz4MWWOQDjqPSLQTUFahapcYV9vH3Mjq2w2Ykg+bcmxqvkXKhbrDpa59Ftca72xuirAtxEkIbf9ec9Kz7AFoXQMavPQgLps5tJG9CSquDbyHJk6QUZK6CapIwZyGE8eJY1CzzmS7EWkt1kkhwqdD3Ut9MrL9+nM5bCHMcavW9sfy+zyTQgAVIFc7+7dWVR/cPFdbhXeN1yoJokuom0X2q4kUhuQsgI4IHf7WZQ=
    - secure: KLRlEjG59XuHpi3IPuzEObcXkS9PN2vSQpE3xVqx8aAzXbLBMgSs3Rh5xp+z4aZZfjBBTRfUT0hZ2wlUIvHEuxZcIVvt9YlvPM0eakKrW1dQH1i1W6mHn4lqNsw/Y7Klo8f2/7Q1UW43iFkQjDXAyNTyyUNoKK41bf/B5kNEcOzGWtD06M/CqpjFr+KOIRemPdOeQYSNZqlEKP5fdZCWwRELO7jgpnQ32k+HftGWXV7QjcLTLNX3MuOKXjUp4csjRxrhCPMwWnDpagG5PNhN7ydbOwGYrsUphCpQRqWnv4OdKO+dzXierKY+tWLkkZklX9/qLNdnemrgBXwJbp21Tzb8KXM7ImTtBeuGlTuM86LJ3e9g+OOPWv72FS3d80ssJqaoBu8rkZZC6oKV4Z1iRI5afliAs/XI5f7Iv18bMmvCKPvJf4c/DssImv+xFNAwjtMrLDOSPIkmsBlcA6YWxg/MJHZcIKVwJRqB5JITYP4L6wEzgmcHJMw0DXyQNpAIvINEj3rb6zJBj4l8Bw4mAhBhHNPnwryB2swpAsQMeLa0sV0q1JbPtumLHklPv5sm81p2HLLAB2m2fb2DjW1seGScOO9vJM8mrU68aHu89Tb9R2sZuvlf58PFoSloTYdgGPN3CtoazN88RmVNlf2GBKS9J7F/JLY4xpwV7LKbJug=
install:
  - make setup
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - make test
  - make build
  - cd dist && python -m SimpleHTTPServer &
  - sleep 2
  - curl --retry 5 --retry-delay 2 "localhost:8000"
  - make test-e2e
deploy:
  provider: script
  script:
    - make deploy
  on:
    branch: release
  skip_cleanup: true
