language: node_js
node_js:
  - '6.5'
env:
  global:
    - NODE_ENV=production
    - SENTRY_DSN=https://d7512af0e14e4b2aa61dd44cff67e1cb@app.getsentry.com/77181
    - secure: BjecDYffg85ZQnXLHTzePtmqZ03SliT+uRJUUxa/CDJwuQvhwDpeTNGI6qXMCVrXphV9sJhFx55Y+bs9b90YAxEC6ZaJGt874Qe6tcbuur4CUpJjrNQCG1MAollNX6xljGHY7kphLSD8A7lT1TQvBB3xNUKmmkx/tncqPYCl7HggdxIoBPbvMpRvg1pwBa8yTID+WUqPImneBiVFKNS4mBWauOGH6d5ILppAyyRlZ17y061FDMHLbX85mOjiPuFQ22X45zdGtitF10gxMpfAUNeUIGl9+hbloZFEHzc4f0uL/XoUJ5V2xfFH4r092GfbRf56jZDQVKgD/657JFaJvjf1yF7g9GwTdDY6qtdgb82MkEx5Km7y1KZKfvrhigMDMgRGXqN6DCmT+PoJ1vCPf4KVkkALfTL6LeLg+QBsQvYteQiqX9V3Z/4vXtoVzKVeNmhU34pruMk2UR6gojEQPF9d9fxV/kwe/KPigWeahNeZDAjlxgsSeJ5nCzeCW5bV2tR6UpSzy3u7QqL7XgUj8M1y7j1i2q9tTgqAMc9nMDHXfcBkllTCKfQy+T7X2M07ePC/4Appll1xieakWsBgSZNu9LRHrVZJu84SDbnHTcZdmgYwParBWkCo/MwDC1dAqD9Zw+aG7hklFja2vMwXf/P8BdlmfENh5CYeEqXrh30=
    - secure: iAXSJrXZQf1kJcgSKATj+VrKYnWUUyGxSLpcnzWAg4mkmsx9x7lQFWnHqIR0PzAvr8vnRrgGK4IeU+zKrC5i4tCLVH2Ohu6TFAnrFOVGsIXyX+rh9Q9VrtNVRmy4gPg1mBRiQDSAHtQTnWOLO6DaWpHwEVBV4gunjv92YJffxt75j6BiK4n2zJTrnA5nMR69qxINX2qHiSABIIFxARVg4njhCB5X1VROCR9AaAlJD7w6KGkW9211iBeAZCNg9ibk21oiLoMISXNnE/3p7DVJuAgNqoKPR5Z+Prk9hJmhQq2u7+lErec73q86/YvHNCqK5L4TatXiVCepktMruoRDzeGkdBPEasXXkZ5kahpfUZ1+lI+MjDVCzurPF+i4JTrgMlZC831vPTkEQhXxtcKLlpEMHVCgNtwunstpGPZRhGBJf+0eaz5EETwh+0YCURlDUVPsdS4tF9kvF70heNRx0nWoGXHVl9BmODeqMRlpb4ewGmPVLd4L/H/8G2UIAnf1+jPEPgwjaHCSN4eA/Ny65PVLrL24IhAb+C/UJ3DHrbY27V8qQb7Ix9Ds3/IslTgBJlzmoGg7hMNWyO32vkpdWVEad8ACwAjsikv6knXaZoTYu8l22jvhfpSSc6LiAqZxuNVSyE7+OFNJznqbr/TAPauIMwJ3Z/bWpnvtHRUBB1k=
    - secure: cYaP50alqZhv13zjCWOOvtACMeyR4FSHxBr7bO/1iOD87NTzqgFZIFTDQqtgxgwn3WdaPAGZx+lrDB5x8mJYqSUCp6tTjQ7GNmRg+dpMz2GVKXFQ2wTyEOsWAUmy0cY2Otwb5i6uTmEsZMXrDya4eGFyVBgn/1mPByRuKG1oOM/qDLAK2A52aFyIPbYUsWn25u+U197hoddA9RMzDBtnB4vmcNI6p43q+qYZF7TIsDXklEqS6jt+a8WcK7TxMkCfbigM9rQLYZdy/diGMKMiTsWjKYlV3h/vbYT+CKwbGIHgk/3BhIvm5lkiKwWSyy0syqZA8BJzBVvGdVLgkSdJVaIaJP8t3RvSaMwTMz+alFmI2k6aKdlyQn4RT64WANHnHVBI4aEt6I7GDOVjWiwxpaTmAaZ1wdBhm9HjCCay9dg356n0PBn/vbUYILsltfWo7qak7wML+tp2SVNcgCXop1IoZLXF+OHLn6uss23dXOpzhn5cxouTGPDK9FDuwf03YN6IpuXbmg9un1T6VojGNGQqxTfpkQHUPnIw7gwSoKu5sjsa+Fy9+zLJ2JB5xNDchWl+u7mf9mIoncZ4S522icIlC9KILjtkhmPETxY3xsPpItEjyovbQ6YbS3K0nmR2mq6+SQA1eOtPKQuCURKbhTpOEbOHhvbCY+0aFwdNoak=
cache:
  directories:
    - node_modules
install:
  - npm prune
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
  - npm run build
  - cd dist && python -m SimpleHTTPServer &
  - sleep 2
  - curl --retry 5 --retry-delay 2 "localhost:8000"
  - npm run test:e2e
deploy:
  provider: script
  script:
    - npm run deploy
  on:
    branch: release
  skip_cleanup: true
