language: node_js
node_js:
  - '6.5'
env:
  global:
    - SENTRY_DSN=https://d7512af0e14e4b2aa61dd44cff67e1cb@app.getsentry.com/77181
    - secure: cYaP50alqZhv13zjCWOOvtACMeyR4FSHxBr7bO/1iOD87NTzqgFZIFTDQqtgxgwn3WdaPAGZx+lrDB5x8mJYqSUCp6tTjQ7GNmRg+dpMz2GVKXFQ2wTyEOsWAUmy0cY2Otwb5i6uTmEsZMXrDya4eGFyVBgn/1mPByRuKG1oOM/qDLAK2A52aFyIPbYUsWn25u+U197hoddA9RMzDBtnB4vmcNI6p43q+qYZF7TIsDXklEqS6jt+a8WcK7TxMkCfbigM9rQLYZdy/diGMKMiTsWjKYlV3h/vbYT+CKwbGIHgk/3BhIvm5lkiKwWSyy0syqZA8BJzBVvGdVLgkSdJVaIaJP8t3RvSaMwTMz+alFmI2k6aKdlyQn4RT64WANHnHVBI4aEt6I7GDOVjWiwxpaTmAaZ1wdBhm9HjCCay9dg356n0PBn/vbUYILsltfWo7qak7wML+tp2SVNcgCXop1IoZLXF+OHLn6uss23dXOpzhn5cxouTGPDK9FDuwf03YN6IpuXbmg9un1T6VojGNGQqxTfpkQHUPnIw7gwSoKu5sjsa+Fy9+zLJ2JB5xNDchWl+u7mf9mIoncZ4S522icIlC9KILjtkhmPETxY3xsPpItEjyovbQ6YbS3K0nmR2mq6+SQA1eOtPKQuCURKbhTpOEbOHhvbCY+0aFwdNoak=
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm prune
  - npm install
  - node_modules/.bin/webdriver-manager update
script:
  - npm run lint
  - npm run test
  - npm run build
  - cd dist && python -m SimpleHTTPServer &
  - sleep 2
  - curl --retry 5 --retry-delay 2 "localhost:8000"
  - npm run test-e2e
deploy:
  provider: script
  script:
    - npm run deploy
  on:
    branch: release
  skip_cleanup: true
