language: node_js
node_js:
  - '6.1'
env:
  global:
    - NODE_ENV=production
    - SURGE_DOMAIN=furious-spider.surge.sh
    - secure: cYaP50alqZhv13zjCWOOvtACMeyR4FSHxBr7bO/1iOD87NTzqgFZIFTDQqtgxgwn3WdaPAGZx+lrDB5x8mJYqSUCp6tTjQ7GNmRg+dpMz2GVKXFQ2wTyEOsWAUmy0cY2Otwb5i6uTmEsZMXrDya4eGFyVBgn/1mPByRuKG1oOM/qDLAK2A52aFyIPbYUsWn25u+U197hoddA9RMzDBtnB4vmcNI6p43q+qYZF7TIsDXklEqS6jt+a8WcK7TxMkCfbigM9rQLYZdy/diGMKMiTsWjKYlV3h/vbYT+CKwbGIHgk/3BhIvm5lkiKwWSyy0syqZA8BJzBVvGdVLgkSdJVaIaJP8t3RvSaMwTMz+alFmI2k6aKdlyQn4RT64WANHnHVBI4aEt6I7GDOVjWiwxpaTmAaZ1wdBhm9HjCCay9dg356n0PBn/vbUYILsltfWo7qak7wML+tp2SVNcgCXop1IoZLXF+OHLn6uss23dXOpzhn5cxouTGPDK9FDuwf03YN6IpuXbmg9un1T6VojGNGQqxTfpkQHUPnIw7gwSoKu5sjsa+Fy9+zLJ2JB5xNDchWl+u7mf9mIoncZ4S522icIlC9KILjtkhmPETxY3xsPpItEjyovbQ6YbS3K0nmR2mq6+SQA1eOtPKQuCURKbhTpOEbOHhvbCY+0aFwdNoak=
    - secure: NgeMO7IKW2JbdWQpQB0ambUrhkJHcsAY4LMdnDUOP3sZcVYV238G80dsePBH+8ISoMHvePWoiE+wyY5AUPSRaX1nt5h/2Wl8He4xTCB9dz54L6wVi54GPDcVimBzSkrQW5SgGRde1hJWvDBYhVXNLRa+lwXtvQO3NdEEVJxpb0nWhywW4RZ9jb1Iqqvi70EN4mQM9M6onrcdtJM2F7woNNOO0FnPFgXLK2ZwzbpJNz68nBWCzW1cDyGi+Eaq3cvH6h31UZ2VPOOUTediTlTFGu7OH/gnYkhkJqH3uUdAJOvfnIYHLHw3byceV1YShz9QptxUSP7TV7BV02dNiZ8A37HmkrcX+ugdHtflyc1lTGQMVqJkNUWKBWgZnVd5t1IYKUMVrz0XLB1Oja195zctIFjnWnBp8nOL4wg3z14/LE7lnFb/PDhN94+EFBHY9feVhdOQc3M/AGX14PRn5fQ3UAVvfosJdScookXZI/SALuva01aInQXc8q+FoCUNYtZlhf4cwgnBFJ3nJzGv9OCcnJLXqH1W9tph4VNWRYvtFMLftpvHjJzjd0proOIlGI/0sP4ACtWBLRD9nZ7li98VytOW2tMbdT/KXBTZlMqsNGNTaZjQgHK7YE/CD5oRKOcnW2d/SieMKlOnfcBsooZGpVpvHWEd6wOt1xfYseVwU7g=
install:
  - make setup
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - make test
  - make build
  - cd dist && python -m SimpleHTTPServer &
  - sleep 2
  - curl --retry 5 --retry-delay 2 "localhost:8000"
  - make test-e2e
deploy:
  provider: script
  script:
    - make deploy
  on:
    branch: release
  skip_cleanup: true
