environment:
  NODE_VERSION: "6.5"
  FIREBASE_TOKEN: "firebase_token"
  SENTRY_DSN: "sentry_dsn"
  SEGMENT_API_KEY: "segment_api_key"

cache:
  - node_modules

install:
  - ps: Install-Product node $env:NODE_VERSION
  - npm prune
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
