import _ from 'lodash';

export function postFactory(options = {}) {
  const {
    playable,
  } = _.defaults(options, {
    playable: true,
  });

  return {
    kind: 't3',
    data: {
      contest_mode: false,
      banned_by: null,
      domain: 'youtube.com',
      subreddit: 'listentothis',
      selftext_html: null,
      selftext: '',
      likes: null,
      suggested_sort: null,
      user_reports: [],
      secure_media: {
        type: 'youtube.com',
        oembed: {
          provider_url: 'https://www.youtube.com/',
          title: 'Too Stupid by Father Time',
          type: 'video',
          html: '&lt;iframe width="459" height="344" src="https://www.youtube.com/embed/8xznXrLHIh8?feature=oembed" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;',
          thumbnail_width: 480,
          height: 344,
          width: 459,
          version: '1.0',
          author_name: 'Scott Time',
          provider_name: 'YouTube',
          thumbnail_url: 'https://i.ytimg.com/vi/8xznXrLHIh8/hqdefault.jpg',
          thumbnail_height: 360,
          author_url: 'https://www.youtube.com/user/TheLastRockHope',
        },
      },
      saved: false,
      id: '5cqfyl',
      gilded: 0,
      secure_media_embed: {
        content: '&lt;iframe width="459" height="344" src="https://www.youtube.com/embed/8xznXrLHIh8?feature=oembed" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;',
        width: 459,
        scrolling: false,
        height: 344,
      },
      clicked: false,
      report_reasons: null,
      author: 'cobiti',
      media: {
        type: 'youtube.com',
        oembed: {
          provider_url: 'https://www.youtube.com/',
          title: 'Too Stupid by Father Time',
          type: 'video',
          html: '&lt;iframe width="459" height="344" src="https://www.youtube.com/embed/8xznXrLHIh8?feature=oembed" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;',
          thumbnail_width: 480,
          height: 344,
          width: 459,
          version: '1.0',
          author_name: 'Scott Time',
          provider_name: 'YouTube',
          thumbnail_url: 'https://i.ytimg.com/vi/8xznXrLHIh8/hqdefault.jpg',
          thumbnail_height: 360,
          author_url: 'https://www.youtube.com/user/TheLastRockHope',
        },
      },
      name: 't3_5cqfyl',
      score: 0,
      approved_by: null,
      over_18: false,
      removal_reason: null,
      hidden: false,
      preview: {
        images: [
          {
            source: {
              url: 'https://i.redditmedia.com/ROIwzRljrMYcwmNeDBumDf3TDgh3plPIyjOq_kuBRZc.jpg?s=2883744979afec77156251a077e0fbf3',
              width: 480,
              height: 360,
            },
            resolutions: [
              {
                url: 'https://i.redditmedia.com/ROIwzRljrMYcwmNeDBumDf3TDgh3plPIyjOq_kuBRZc.jpg?f…faces%2Centropy&amp;arh=2&amp;w=108&amp;s=b4ccb73a540700bb337caa3702319c67',
                width: 108,
                height: 81,
              },
              {
                url: 'https://i.redditmedia.com/ROIwzRljrMYcwmNeDBumDf3TDgh3plPIyjOq_kuBRZc.jpg?f…faces%2Centropy&amp;arh=2&amp;w=216&amp;s=5ecaeb8052c2a7bbbfc77a52ece474bd',
                width: 216,
                height: 162,
              },
              {
                url: 'https://i.redditmedia.com/ROIwzRljrMYcwmNeDBumDf3TDgh3plPIyjOq_kuBRZc.jpg?f…faces%2Centropy&amp;arh=2&amp;w=320&amp;s=73a8ac38952bb52d9b6f078d66cd4d4d',
                width: 320,
                height: 240,
              },
            ],
            variants: {},
            id: 'xI81E_xAqwILPyrj6O39Lr3Cq7nqtcvceu6zvC6MXVU',
          },
        ],
      },
      thumbnail: 'http://b.thumbs.redditmedia.com/hBOLGB1Os62s8tVFPFbLq8w6Xd4mvQYXjS3YBoq0GKs.jpg',
      subreddit_id: 't5_2qxzy',
      edited: false,
      link_flair_css_class: null,
      author_flair_css_class: null,
      downs: 0,
      mod_reports: [],
      archived: false,
      media_embed: {
        content: '&lt;iframe width="459" height="344" src="https://www.youtube.com/embed/8xznXrLHIh8?feature=oembed" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;',
        width: 459,
        scrolling: false,
        height: 344,
      },
      post_hint: 'rich:video',
      is_self: false,
      hide_score: true,
      spoiler: false,
      permalink: '/r/listentothis/comments/5cqfyl/father_time_too_stupid_melodic_rock_2011/',
      locked: false,
      stickied: false,
      created: 1479080525,
      url: playable
        ? 'https://www.youtube.com/watch?v=8xznXrLHIh8'
        : 'https://www.vimeo.com/abc123',
      author_flair_text: null,
      quarantine: false,
      title: 'Father Time - Too Stupid [Melodic Rock] (2011)',
      created_utc: 1479051725,
      link_flair_text: null,
      distinguished: null,
      num_comments: 1,
      visited: false,
      num_reports: null,
      ups: 0,
    },
  };
}
